name: screen_capturer
description: This plugin allows Flutter desktop apps to capture screenshots.
version: 0.1.2
homepage: https://github.com/leanflutter/screen_capturer

platforms:
  linux:
  macos:
  windows:

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  ffi: ^2.0.2
  win32: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

dependency_overrides: 
  path_provider_windows: ^2.1.6

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: ScreenCapturerPlugin
      windows:
        pluginClass: ScreenCapturerPlugin
