name: screen_capturer
description: This plugin allows Flutter desktop apps to capture screenshots.
version: 0.1.2
homepage: https://github.com/leanflutter/screen_capturer

platforms:
  linux:
  macos:
  windows:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  ffi: ^2.0.1
  win32: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: ScreenCapturerPlugin
      windows:
        pluginClass: ScreenCapturerPlugin
